baseURL = 'https://i32.co.nz/'
languageCode = 'en-us'
title = 'i32 Labs'

[menus]
  [[menus.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 10

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
