baseURL = 'https://i32.co.nz/'
languageCode = 'en-us'
title = 'i32 Labs'

[menus]
  [[menus.main]]
    name = 'Nebula'
    pageRef = '/nebula'
    weight = 10

  [[menus.main]]
    name = 'Press Kit'
    pageRef = '/press'
    weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
